package com.liftpath.helpers

import android.util.Log
import com.liftpath.models.ExerciseLibraryItem
import com.liftpath.models.MovementPattern
import com.liftpath.models.PlanExerciseSelectionType
import com.liftpath.models.PlanExerciseSlot
import com.liftpath.models.PlanSlotType
import com.liftpath.models.SetIntent
import com.liftpath.models.TrainingData
import com.liftpath.models.WorkoutPlan
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID

object WorkoutPlanMarkdownHelper {

    private const val TAG = "WorkoutPlanMarkdown"
    private val PLAN_HEADING = Regex("""^## Plan:\s*(.+)""")
    private val NOTES_LINE = Regex("""^Notes:\s*(.*)""", RegexOption.IGNORE_CASE)

    fun buildSpecMarkdown(trainingData: TrainingData): String {
        val sb = StringBuilder()

        sb.append("# LiftPath Workout Plan Spec\n")
        sb.append("_Generated by LiftPath — hand this file to your AI, ask it to add \"## Plan:\" sections, then import the file back._\n\n")
        sb.append("---\n\n")

        sb.append("## How to Create a Plan\n\n")
        sb.append("Add one or more plan sections **anywhere in this file** using this template:\n\n")
        sb.append("```\n")
        sb.append("## Plan: [Your Plan Name]\n")
        sb.append("Notes: [Optional description]\n\n")
        sb.append("| Exercise Name | Exercise ID | Sets | Reps | Intent | RPE Target | Rest (sec) | Notes | Family ID |\n")
        sb.append("|---|---|---|---|---|---|---|---|---|\n")
        sb.append("| __warmup__ |  |  |  |  |  |  |  |  |\n")
        sb.append("| Bench Press | 1 | 4 | 8-10 | STRENGTH | 8.0 | 120 | Keep shoulder blades back |  |\n")
        sb.append("| Horizontal Push (any) |  | 3 | 10-12 | BUILD | 7.5 | 90 |  | chest_press |\n")
        sb.append("| __cooldown__ |  |  |  |  |  |  |  |  |\n")
        sb.append("```\n\n")

        sb.append("### Field Reference\n\n")
        sb.append("| Field | Required | Format |\n")
        sb.append("|---|---|---|\n")
        sb.append("| Exercise Name | No | Informational only — the ID is what matters |\n")
        sb.append("| Exercise ID | Conditional | Integer from the exercise table below. Leave blank for `__warmup__` / `__cooldown__` sentinels or when using a Family ID instead. |\n")
        sb.append("| Sets | No | Integer, e.g. `4` |\n")
        sb.append("| Reps | No | **Rep count only** — `8`, `8-10`, or `10+`. NEVER put a duration or time here (e.g. do NOT write `30 sec` or `30-60`). For timed holds, leave this blank and describe the duration in Notes. |\n")
        sb.append("| Intent | No | `STRENGTH`, `BUILD`, `FLUSH`, or `WARMUP` |\n")
        sb.append("| RPE Target | No | `6.0`–`10.0`, or blank |\n")
        sb.append("| Rest (sec) | No | Rest between sets in whole seconds, e.g. `120`. Leave blank if not applicable. |\n")
        sb.append("| Notes | No | Free text (avoid pipe `|` characters). Use this for hold durations, technique cues, etc. |\n")
        sb.append("| Family ID | No | **(V3 optional)** A family ID from the families table below. If Exercise ID is blank and Family ID is set, the slot is a flexible family slot — the user can choose any matching exercise at workout time. |\n\n")
        sb.append("**Warmup / Cool-down:** Insert a row with `__warmup__` or `__cooldown__` in the Exercise Name column and leave all other columns blank. Always place `__warmup__` as the first row and `__cooldown__` as the last row of the plan.\n\n")

        sb.append("---\n\n")

        // Exercise families for V3 family-slot support
        val families = trainingData.exerciseFamilies ?: DefaultExercisesHelper.DEFAULT_FAMILIES
        if (families.isNotEmpty()) {
            sb.append("## Available Exercise Families (V3 Family Slots)\n\n")
            sb.append("Use these Family IDs in column 9 to create flexible slots:\n\n")
            sb.append("| Family Name | Family ID | Movement Pattern | Body Region |\n")
            sb.append("|---|---|---|---|\n")
            for (f in families.sortedBy { it.name }) {
                sb.append("| ${f.name} | ${f.id} | ${f.movementPattern?.name ?: ""} | ${f.bodyRegion?.name ?: ""} |\n")
            }
            sb.append("\n")
        }

        sb.append("---\n\n")
        sb.append("## Available Exercises\n\n")
        sb.append("| Exercise Name | ID | Region | Pattern | Equipment | Tier | Primary Muscles |\n")
        sb.append("|---|---|---|---|---|---|---|\n")

        for (ex in trainingData.exerciseLibrary.sortedBy { it.id }) {
            val muscles = ex.primaryTargets.joinToString(", ") { it.name }
            sb.append("| ${ex.name} | ${ex.id} | ${ex.region?.name ?: ""} | ${ex.pattern?.name ?: ""} | ${ex.equipment?.name ?: ""} | ${ex.tier?.name ?: ""} | $muscles |\n")
        }

        return sb.toString()
    }

    fun parsePlansFromMarkdown(
        markdown: String,
        exerciseLibrary: List<ExerciseLibraryItem>
    ): List<WorkoutPlan> {
        val exerciseById = exerciseLibrary.associateBy { it.id }
        // Stable family IDs from the default catalog — used to validate column 9 values
        val knownFamilyIds: Set<String> = DefaultExercisesHelper.DEFAULT_FAMILIES.map { it.id }.toSet()
        val familyById = DefaultExercisesHelper.DEFAULT_FAMILIES.associateBy { it.id }
        val lines = markdown.lines()

        // Split the document into (planName, sectionLines) pairs
        val sections = mutableListOf<Pair<String, List<String>>>()
        var i = 0
        while (i < lines.size) {
            val match = PLAN_HEADING.find(lines[i])
            if (match != null) {
                val name = match.groupValues[1].trim()
                val body = mutableListOf<String>()
                i++
                while (i < lines.size && !PLAN_HEADING.containsMatchIn(lines[i])) {
                    body.add(lines[i])
                    i++
                }
                sections.add(name to body)
            } else {
                i++
            }
        }

        val today = SimpleDateFormat("yyyy/MM/dd", Locale.US).format(Date())
        val plans = mutableListOf<WorkoutPlan>()

        for ((planName, body) in sections) {
            var notes: String? = null
            val tableRows = mutableListOf<List<String>>()
            var inTable = false
            var headerSkipped = false
            var separatorSkipped = false

            for (line in body) {
                // Detect Notes: line outside of tables
                if (!inTable) {
                    val notesMatch = NOTES_LINE.find(line.trim())
                    if (notesMatch != null && notes == null) {
                        val v = notesMatch.groupValues[1].trim()
                        if (v.isNotEmpty()) notes = v
                        continue
                    }
                }

                if (line.contains("|")) {
                    inTable = true
                    if (!headerSkipped) { headerSkipped = true; continue }
                    if (!separatorSkipped) { separatorSkipped = true; continue }

                    val cells = line.split("|").map { it.trim() }
                    // After splitting "| A | B |" we get ["", "A", "B", ""] — drop empty edges
                    val data = cells.drop(1).dropLast(1)
                    if (data.size >= 2) tableRows.add(data)
                } else if (inTable && line.isBlank()) {
                    // Blank line ends the current table
                    inTable = false
                    headerSkipped = false
                    separatorSkipped = false
                }
            }

            val slots = mutableListOf<PlanExerciseSlot>()
            val legacyIds = mutableListOf<Int>()

            for (cells in tableRows) {
                val nameCellRaw = cells.getOrNull(0) ?: ""
                val idCellRaw = cells.getOrNull(1) ?: ""

                // Detect warmup/cooldown sentinel rows
                val nameLower = nameCellRaw.trim().lowercase()
                if (nameLower == "__warmup__" || (idCellRaw.isBlank() && nameLower.contains("warmup"))) {
                    slots.add(PlanExerciseSlot(id = UUID.randomUUID().toString(), slotType = PlanSlotType.WARMUP))
                    continue
                }
                if (nameLower == "__cooldown__" || (idCellRaw.isBlank() && nameLower.contains("cooldown"))) {
                    slots.add(PlanExerciseSlot(id = UUID.randomUUID().toString(), slotType = PlanSlotType.COOLDOWN))
                    continue
                }

                val exerciseIdParsed = idCellRaw.toIntOrNull()
                val familyIdCell = cells.getOrNull(8)?.trim()?.takeIf { it.isNotEmpty() }

                val setsTarget = cells.getOrNull(2)?.toIntOrNull()
                val repsTarget = cells.getOrNull(3)?.takeIf { it.isNotEmpty() }
                val intentStr = cells.getOrNull(4) ?: ""
                val intent = SetIntent.values()
                    .firstOrNull { it.value.equals(intentStr, ignoreCase = true) }
                val rpeTarget = cells.getOrNull(5)?.toFloatOrNull()
                val restTimeSeconds = cells.getOrNull(6)?.toIntOrNull()
                val slotNotes = cells.getOrNull(7)?.takeIf { it.isNotEmpty() }

                if (exerciseIdParsed == null && familyIdCell != null && familyIdCell in knownFamilyIds) {
                    // V3 FAMILY_SLOT row: blank Exercise ID, valid Family ID in column 9
                    val family = familyById[familyIdCell]
                    slots.add(
                        PlanExerciseSlot(
                            id = UUID.randomUUID().toString(),
                            selectionType = PlanExerciseSelectionType.FAMILY_SLOT,
                            familyId = familyIdCell,
                            movementPattern = family?.movementPattern,
                            defaultIntent = intent,
                            restTimeSeconds = restTimeSeconds,
                            rpeTarget = rpeTarget,
                            setsTarget = setsTarget,
                            repsTarget = repsTarget,
                            notes = slotNotes
                        )
                    )
                    continue
                }

                val exerciseId = exerciseIdParsed ?: continue
                if (!exerciseById.containsKey(exerciseId)) {
                    Log.w(TAG, "Exercise ID $exerciseId not in library — skipping")
                    continue
                }

                slots.add(
                    PlanExerciseSlot(
                        id = UUID.randomUUID().toString(),
                        exerciseId = exerciseId,
                        defaultIntent = intent,
                        restTimeSeconds = restTimeSeconds,
                        rpeTarget = rpeTarget,
                        setsTarget = setsTarget,
                        repsTarget = repsTarget,
                        notes = slotNotes,
                        selectionType = PlanExerciseSelectionType.SPECIFIC_VARIANT
                    )
                )
                legacyIds.add(exerciseId)
            }

            if (slots.isEmpty()) {
                Log.w(TAG, "Plan \"$planName\" has no valid exercises — skipping")
                continue
            }

            plans.add(
                WorkoutPlan(
                    id = UUID.randomUUID().toString(),
                    name = planName,
                    exerciseIds = legacyIds,
                    workoutType = "build",
                    exerciseConfigs = slots,
                    notes = notes,
                    createdDate = today,
                    planSchemaVersion = 2
                )
            )
        }

        return plans
    }
}
